eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    #url: jdbc:mysql://mysql-db-instance.c74qewyu02qd.ca-central-1.rds.amazonaws.com:3306/restaurantdb
    url: jdbc:mysql://localhost:3306/restaurantdb
    password: admin
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true